[project]
name = "repl-nix-stocksavvyapp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas-ta>=0.3.14b0",
    "plotly>=5.24.1",
    "streamlit>=1.40.1",
    "yfinance>=0.2.50",
]
