[server]
headless = true
enableCORS = true
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = true

[markup]
unsafe_allow_html = true
