ALPHA_VANTAGE_API_KEY = "${ALPHA_VANTAGE_API_KEY}"
COINMARKETCAP_API_KEY = "b4d181e2-e761-479c-8522-d380ec813536"

[theme]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"
